/**
 * BAJAJ PARIVAHAN - Full Flat Menu Database Mock Matrix
 * This dataset replicates the exact database array format for runtime tree rendering.
 */
export const mockFlatMenuData = [
  // ==========================================
  // TIER 1: PRIMARY ROOT MODULES
  // ==========================================
  {
    id: "M00001",
    label: "Master",
    path: "/masters",
    parent: null,
    active: true,
  },
  {
    id: "T00001",
    label: "Transaction",
    path: "/transactions",
    parent: null,
    active: true,
  },
  {
    id: "R00001",
    label: "Report",
    path: "/reports",
    parent: null,
    active: true,
  },

  // ==========================================
  // MASTER SECTION BRANCHES (TIER 2)
  // ==========================================
  {
    id: "MT0001",
    label: "TRANSPORT",
    path: null,
    parent: "M00001",
    active: true,
  },
  {
    id: "MA0001",
    label: "ACCOUNTS",
    path: null,
    parent: "M00001",
    active: true,
  },

  // --- MASTER -> TRANSPORT Operational Leaves (Tier 3) ---
  {
    id: "MTT001",
    label: "Consignor / Consignee",
    path: "/masters/consignor-consignee",
    parent: "MT0001",
    active: true,
  },
  {
    id: "MTT002",
    label: "Charger",
    path: "/masters/charger",
    parent: "MT0001",
    active: true,
  },
  {
    id: "MTT003",
    label: "Broker",
    path: "/masters/broker",
    parent: "MT0001",
    active: true,
  },
  {
    id: "MTT004",
    label: "Agent",
    path: "/masters/agent",
    parent: "MT0001",
    active: true,
  },
  {
    id: "MTT005",
    label: "Destination",
    path: "/masters/destination",
    parent: "MT0001",
    active: true,
  },
  {
    id: "MTT006",
    label: "Product",
    path: "/masters/product",
    parent: "MT0001",
    active: true,
  },
  {
    id: "MTT007",
    label: "Packet Mode",
    path: "/masters/packet-mode",
    parent: "MT0001",
    active: true,
  },
  {
    id: "MTT008",
    label: "Truck Owner",
    path: "/masters/truck-owner",
    parent: "MT0001",
    active: true,
  },
  {
    id: "MTT009",
    label: "Market Truck",
    path: "/masters/market-truck",
    parent: "MT0001",
    active: true,
  },
  {
    id: "MTT010",
    label: "Godown",
    path: "/masters/godown",
    parent: "MT0001",
    active: true,
  },
  {
    id: "MTT011",
    label: "Loading / Unloading Person",
    path: "/masters/labor",
    parent: "MT0001",
    active: true,
  },
  {
    id: "MTT012",
    label: "Transit Route",
    path: "/masters/transit-route",
    parent: "MT0001",
    active: true,
  },
  {
    id: "MTT013",
    label: "Driver",
    path: "/masters/driver",
    parent: "MT0001",
    active: true,
  },
  {
    id: "MTT014",
    label: "Driver Allotment",
    path: "/masters/driver-allotment",
    parent: "MT0001",
    active: true,
  },
  {
    id: "MTT015",
    label: "Door Delivery Rate",
    path: "/masters/door-delivery-rate",
    parent: "MT0001",
    active: true,
  },
  {
    id: "MTT016",
    label: "Door Delivery Exp Rate",
    path: "/masters/door-delivery-expense-rate",
    parent: "MT0001",
    active: true,
  },
  {
    id: "MTT017",
    label: "Transit Day",
    path: "/masters/transit-days",
    parent: "MT0001",
    active: true,
  },
  {
    id: "MTT018",
    label: "MR Charges",
    path: "/masters/mr-charges",
    parent: "MT0001",
    active: true,
  },

  // --- MASTER -> ACCOUNTS Operational Leaves (Tier 3) ---
  {
    id: "MAA001",
    label: "Zone",
    path: "/masters/zone",
    parent: "MA0001",
    active: true,
  },
  {
    id: "MAA002",
    label: "Branch",
    path: "/masters/branch",
    parent: "MA0001",
    active: true,
  },
  {
    id: "MAA003",
    label: "Main Group",
    path: "/masters/main-group",
    parent: "MA0001",
    active: true,
  },
  {
    id: "MAA004",
    label: "Sub Group",
    path: "/masters/sub-group",
    parent: "MA0001",
    active: true,
  },
  {
    id: "MAA005",
    label: "Debtor's Ledger",
    path: "/masters/debtors-ledger",
    parent: "MA0001",
    active: true,
  },
  {
    id: "MAA006",
    label: "General Ledger",
    path: "/masters/general-ledger",
    parent: "MA0001",
    active: true,
  },
  {
    id: "MAA007",
    label: "Book Code",
    path: "/masters/book-code",
    parent: "MA0001",
    active: true,
  },
  {
    id: "MAA008",
    label: "Opening Balance",
    path: "/masters/opening-balance",
    parent: "MA0001",
    active: true,
  },
  {
    id: "MAA009",
    label: "Payment Party",
    path: "/masters/payment-party",
    parent: "MA0001",
    active: true,
  },

  // ==========================================
  // TRANSACTION SECTION BRANCHES (TIER 2)
  // ==========================================
  {
    id: "TT0001",
    label: "TRANSPORT",
    path: null,
    parent: "T00001",
    active: true,
  },
  {
    id: "TA0001",
    label: "ACCOUNTS",
    path: null,
    parent: "T00001",
    active: true,
  },

  // --- TRANSACTION -> TRANSPORT Leaves (Tier 3) ---
  {
    id: "TTT001",
    label: "Consignment Note",
    path: "/transactions/consignment-note",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT002",
    label: "Express Consignment Note",
    path: "/transactions/express-consignment-note",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT003",
    label: "Loading Tally",
    path: "/transactions/loading-tally",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT004",
    label: "Manifest Challan",
    path: "/transactions/manifest-challan",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT005",
    label: "Express Manifest Challan",
    path: "/transactions/express-manifest-challan",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT006",
    label: "Crossing Challan",
    path: "/transactions/crossing-challan",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT007",
    label: "Lorry Freight Memo",
    path: "/transactions/lorry-freight-memo",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT008",
    label: "Godown Arrival",
    path: "/transactions/godown-arrival",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT009",
    label: "POD Submission",
    path: "/transactions/pod",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT010",
    label: "Billing Rate - Party",
    path: "/transactions/billing-rate-party",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT011",
    label: "Billing Rate - General",
    path: "/transactions/billing-rate-general",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT012",
    label: "Extra Charges Setup",
    path: "/transactions/extra-charges-setup",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT013",
    label: "Agent Commission Rate",
    path: "/transactions/agent-commission-rate",
    parent: "TT0001",
    active: true,
  },

  // --- TRANSACTION -> TRANSPORT -> BILL INTERMEDIATE CONTAINER (Tier 3 Container) ---
  { id: "TTT014", label: "Bill", path: null, parent: "TT0001", active: true },
  // --- Deep Leaves for Bill Sub-Group (Tier 4) ---
  {
    id: "TTB001",
    label: "Freight Bill",
    path: "/transactions/bills/freight",
    parent: "TTT014",
    active: true,
  },
  {
    id: "TTB002",
    label: "Supplementary Bill",
    path: "/transactions/bills/supplementary",
    parent: "TTT014",
    active: true,
  },
  {
    id: "TTB003",
    label: "Agency Bill",
    path: "/transactions/bills/agency",
    parent: "TTT014",
    active: true,
  },

  {
    id: "TTT015",
    label: "Bill Submission",
    path: "/transactions/bill-submission",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT016",
    label: "Godown Stock Transfer",
    path: "/transactions/godown-stock-transfer",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT017",
    label: "Gate Pass Submission",
    path: "/transactions/gate-pass-submission",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT018",
    label: "Document Inward",
    path: "/transactions/document-inward",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT019",
    label: "Document Issue",
    path: "/transactions/document-issue",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT020",
    label: "Branch To Branch Document Transfer",
    path: "/transactions/branch-document-transfer",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT021",
    label: "TDS Submission",
    path: "/transactions/tds-submission",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT022",
    label: "Delivery Rate Setup",
    path: "/transactions/delivery-rate",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT023",
    label: "Delivery Extra Charges Setup",
    path: "/transactions/delivery-extra-charges",
    parent: "TT0001",
    active: true,
  },

  // --- TRANSACTION -> TRANSPORT -> TRIP INTERMEDIATE CONTAINER (Tier 3 Container) ---
  { id: "TTT024", label: "Trip", path: null, parent: "TT0001", active: true },
  // --- Deep Leaves for Trip Sub-Group (Tier 4) ---
  {
    id: "TTP001",
    label: "Trip Sheet Entry",
    path: "/transactions/trips/sheet",
    parent: "TTT024",
    active: true,
  },
  {
    id: "TTP002",
    label: "Trip Advance Voucher",
    path: "/transactions/trips/advance",
    parent: "TTT024",
    active: true,
  },
  {
    id: "TTP003",
    label: "Pickup & Delivery Run Sheet",
    path: "/transactions/trips/run-sheet",
    parent: "TTT024",
    active: true,
  },
  {
    id: "TTP004",
    label: "Enroute Expenses Log",
    path: "/transactions/trips/expenses",
    parent: "TTT024",
    active: true,
  },
  {
    id: "TTP005",
    label: "Trip Closing",
    path: "/transactions/trips/closing",
    parent: "TTT024",
    active: true,
  },
  {
    id: "TTP006",
    label: "Trip Settlement",
    path: "/transactions/trips/settlement",
    parent: "TTT024",
    active: true,
  },
  {
    id: "TTP007",
    label: "Delivery Run Sheet (DRS)",
    path: "/transactions/trips/delivery-run-sheet",
    parent: "TTT024",
    active: true,
  },

  {
    id: "TTT025",
    label: "Chargeable Weight Setup",
    path: "/transactions/chargeable-weight",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT026",
    label: "Short / Excess Matrix",
    path: "/transactions/short-excess",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT027",
    label: "Door Delivery Expenses",
    path: "/transactions/door-delivery-expenses",
    parent: "TT0001",
    active: true,
  },
  {
    id: "TTT028",
    label: "Godown Delivery Record",
    path: "/transactions/godown-delivery",
    parent: "TT0001",
    active: true,
  },

  // --- TRANSACTION -> ACCOUNTS Leaves (Tier 3) ---
  {
    id: "TAA001",
    label: "Voucher Entry",
    path: "/transactions/accounts/voucher",
    parent: "TA0001",
    active: true,
  },
  {
    id: "TAA002",
    label: "Journal Entry",
    path: "/transactions/accounts/journal",
    parent: "TA0001",
    active: true,
  },
  {
    id: "TAA003",
    label: "Proforma Voucher",
    path: "/transactions/accounts/proforma-voucher",
    parent: "TA0001",
    active: true,
  },
  {
    id: "TAA004",
    label: "Money Receipt - Full Truck",
    path: "/transactions/accounts/mr-full-truck",
    parent: "TA0001",
    active: true,
  },
  {
    id: "TAA005",
    label: "Money Receipt / Gate Pass",
    path: "/transactions/accounts/mr-gate-pass",
    parent: "TA0001",
    active: true,
  },
  {
    id: "TAA006",
    label: "Contra Entry",
    path: "/transactions/accounts/contra",
    parent: "TA0001",
    active: true,
  },
  {
    id: "TAA007",
    label: "Bank Statement Reconciliation",
    path: "/transactions/accounts/bank-statement",
    parent: "TA0001",
    active: true,
  },
  {
    id: "TAA008",
    label: "Deduction / Refund Adjustment",
    path: "/transactions/accounts/adjustments",
    parent: "TA0001",
    active: true,
  },
  {
    id: "TAA009",
    label: "Creditors Bill Booking",
    path: "/transactions/accounts/creditors-bill",
    parent: "TA0001",
    active: true,
  },
  {
    id: "TAA010",
    label: "Debit / Credit Note",
    path: "/transactions/accounts/debit-credit-note",
    parent: "TA0001",
    active: true,
  },
  {
    id: "TAA011",
    label: "GST Return Submission",
    path: "/transactions/accounts/gst-return",
    parent: "TA0001",
    active: true,
  },
  {
    id: "TAA012",
    label: "Cheque Bounce Log",
    path: "/transactions/accounts/cheque-bounce",
    parent: "TA0001",
    active: true,
  },
  {
    id: "TAA013",
    label: "Door Delivery Expenses Posting",
    path: "/transactions/accounts/door-delivery-post",
    parent: "TA0001",
    active: true,
  },
  {
    id: "TAA014",
    label: "Proforma Voucher - Door Delivery",
    path: "/transactions/accounts/proforma-door-delivery",
    parent: "TA0001",
    active: true,
  },
  {
    id: "TAA015",
    label: "Rate Difference Approval",
    path: "/transactions/accounts/rate-diff-approval",
    parent: "TA0001",
    active: true,
  },
  {
    id: "TAA016",
    label: "MR Ledger Settlement",
    path: "/transactions/accounts/mr-ledger-settlement",
    parent: "TA0001",
    active: true,
  },

  // ==========================================
  // REPORT SECTION BRANCHES (TIER 2)
  // ==========================================
  {
    id: "RT0001",
    label: "TRANSPORT",
    path: null,
    parent: "R00001",
    active: true,
  },
  {
    id: "RA0001",
    label: "ACCOUNTS",
    path: null,
    parent: "R00001",
    active: true,
  },

  // --- REPORT -> TRANSPORT Leaves (Tier 3) ---
  {
    id: "RTT001",
    label: "Tracking / Enquiry System",
    path: "/reports/tracking-enquiry",
    parent: "RT0001",
    active: true,
  },
  {
    id: "RTT002",
    label: "Consignment Statement",
    path: "/reports/consignment-statement",
    parent: "RT0001",
    active: true,
  },
  {
    id: "RTT003",
    label: "Manifest Statement",
    path: "/reports/manifest-statement",
    parent: "RT0001",
    active: true,
  },
  {
    id: "RTT004",
    label: "Lorry Freight Memo Statement",
    path: "/reports/lorry-freight-memo-statement",
    parent: "RT0001",
    active: true,
  },
  {
    id: "RTT005",
    label: "Godown Arrival Statement",
    path: "/reports/godown-arrival-statement",
    parent: "RT0001",
    active: true,
  },
  {
    id: "RTT006",
    label: "Godown Delivery Statement",
    path: "/reports/godown-delivery-statement",
    parent: "RT0001",
    active: true,
  },
  {
    id: "RTT007",
    label: "Daily Delivery Statement",
    path: "/reports/daily-delivery-statement",
    parent: "RT0001",
    active: true,
  },
  {
    id: "RTT008",
    label: "Delivery Statement Summary",
    path: "/reports/delivery-statement",
    parent: "RT0001",
    active: true,
  },
  {
    id: "RTT009",
    label: "Bill Register Statement",
    path: "/reports/bill-statement",
    parent: "RT0001",
    active: true,
  },
  {
    id: "RTT010",
    label: "Stock Inventory Statement",
    path: "/reports/stock-statement",
    parent: "RT0001",
    active: true,
  },
  {
    id: "RTT011",
    label: "Gate Pass Submission Report",
    path: "/reports/gate-pass-statement",
    parent: "RT0001",
    active: true,
  },
  {
    id: "RTT012",
    label: "Payment Collection Statement",
    path: "/reports/payment-collection",
    parent: "RT0001",
    active: true,
  },
  {
    id: "RTT013",
    label: "Document Inward Statement",
    path: "/reports/document-inward",
    parent: "RT0001",
    active: true,
  },
  {
    id: "RTT014",
    label: "Document Issue Statement",
    path: "/reports/document-issue",
    parent: "RT0001",
    active: true,
  },
  {
    id: "RTT015",
    label: "Document Stock Statement",
    path: "/reports/document-stock",
    parent: "RT0001",
    active: true,
  },
  {
    id: "RTT016",
    label: "TDS on Lorry Freight Report",
    path: "/reports/tds-lorry-freight",
    parent: "RT0001",
    active: true,
  },
  {
    id: "RTT017",
    label: "Payment Advice Statement",
    path: "/reports/payment-advice",
    parent: "RT0001",
    active: true,
  },
  {
    id: "RTT018",
    label: "Godown Stock Transfer Statement",
    path: "/reports/godown-stock-transfer",
    parent: "RT0001",
    active: true,
  },
  {
    id: "RTT019",
    label: "Trip Operation Statement",
    path: "/reports/trip-statement",
    parent: "RT0001",
    active: true,
  },

  // --- REPORT -> TRANSPORT -> OUTSTANDING INTERMEDIATE CONTAINER (Tier 3 Container) ---
  {
    id: "RTT020",
    label: "Outstanding",
    path: null,
    parent: "RT0001",
    active: true,
  },
  // --- Deep Leaves for Outstanding Sub-Group (Tier 4) ---
  {
    id: "RTO001",
    label: "Consignment Outstanding",
    path: "/reports/outstanding/consignment",
    parent: "RTT020",
    active: true,
  },
  {
    id: "RTO002",
    label: "Lorry Hire Outstanding",
    path: "/reports/outstanding/lorry-hire",
    parent: "RTT020",
    active: true,
  },
  {
    id: "RTO003",
    label: "Bill Outstanding",
    path: "/reports/outstanding/bill",
    parent: "RTT020",
    active: true,
  },
  {
    id: "RTO004",
    label: "Ageing Analysis Profile",
    path: "/reports/outstanding/ageing-analysis",
    parent: "RTT020",
    active: true,
  },
  {
    id: "RTO005",
    label: "Debtors Reminder System",
    path: "/reports/outstanding/debtors-reminder",
    parent: "RTT020",
    active: true,
  },
  {
    id: "RTO006",
    label: "Credit Money Receipt Log",
    path: "/reports/outstanding/credit-money-receipt",
    parent: "RTT020",
    active: true,
  },
  {
    id: "RTO007",
    label: "Ageing Analysis - Bank Context",
    path: "/reports/outstanding/ageing-bank",
    parent: "RTT020",
    active: true,
  },

  // --- REPORT -> TRANSPORT -> MIS INTERMEDIATE CONTAINER (Tier 3 Container) ---
  { id: "RTT021", label: "MIS", path: null, parent: "RT0001", active: true },
  // --- Deep Leaves for MIS Sub-Group (Tier 4) ---
  {
    id: "RTM001",
    label: "Booking Rate Statement",
    path: "/reports/mis/booking-rate",
    parent: "RTT021",
    active: true,
  },
  {
    id: "RTM002",
    label: "Agent Performance Statement",
    path: "/reports/mis/agent-statement",
    parent: "RTT021",
    active: true,
  },
  {
    id: "RTM003",
    label: "Profitability Breakdown",
    path: "/reports/mis/profitability",
    parent: "RTT021",
    active: true,
  },
  {
    id: "RTM004",
    label: "Freight Memo Evaluation",
    path: "/reports/mis/freight-memo-analysis",
    parent: "RTT021",
    active: true,
  },
  {
    id: "RTM005",
    label: "Debtors Status Overview",
    path: "/reports/mis/debtors-status",
    parent: "RTT021",
    active: true,
  },
  {
    id: "RTM006",
    label: "Daily Analysis Report",
    path: "/reports/mis/daily-analysis",
    parent: "RTT021",
    active: true,
  },
  {
    id: "RTM007",
    label: "Delivery Income Statement",
    path: "/reports/mis/delivery-income",
    parent: "RTT021",
    active: true,
  },
  {
    id: "RTM008",
    label: "Sales Revenue Summary",
    path: "/reports/mis/sales-summary",
    parent: "RTT021",
    active: true,
  },
  {
    id: "RTM009",
    label: "Rate Difference & Shortage Report",
    path: "/reports/mis/rate-diff-shortage",
    parent: "RTT021",
    active: true,
  },
  {
    id: "RTM010",
    label: "Service Turnaround Analysis",
    path: "/reports/mis/service-analysis",
    parent: "RTT021",
    active: true,
  },

  // --- REPORT -> ACCOUNTS Leaves (Tier 3) ---
  {
    id: "RAA001",
    label: "Booking Printing Ledger",
    path: "/reports/accounts/booking-printing",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA002",
    label: "Journal Book Summary",
    path: "/reports/accounts/journal-book",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA003",
    label: "MR Statement - Full Truck Load",
    path: "/reports/accounts/mr-statement-ftl",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA004",
    label: "MR Statement - Parcel Booking",
    path: "/reports/accounts/mr-statement-parcel",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA005",
    label: "Bank Reconciliation Statement",
    path: "/reports/accounts/bank-reconciliation",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA006",
    label: "Daily Balancing Dashboard",
    path: "/reports/accounts/daily-balancing",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA007",
    label: "General Account Ledger",
    path: "/reports/accounts/ledger",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA008",
    label: "Trial Balance Statement",
    path: "/reports/accounts/trial-balance",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA009",
    label: "Profit and Loss Statement",
    path: "/reports/accounts/profit-loss",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA010",
    label: "Balance Sheet Summary",
    path: "/reports/accounts/balance-sheet",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA011",
    label: "Final Accounts Package",
    path: "/reports/accounts/final-accounts",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA012",
    label: "Proforma Voucher Statement",
    path: "/reports/accounts/proforma-voucher-statement",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA013",
    label: "Branch to Branch Transaction Audit",
    path: "/reports/accounts/branch-transactions",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA014",
    label: "Account Confirmation Ledger",
    path: "/reports/accounts/account-confirmation",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA015",
    label: "Cash / Bank Query Terminal",
    path: "/reports/accounts/cash-bank-query",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA016",
    label: "Debtors Statement Ledger",
    path: "/reports/accounts/debtors-statement",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA017",
    label: "Book & Imprest Balancing Log",
    path: "/reports/accounts/book-imprest-balancing",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA018",
    label: "Unadjusted Transaction Audit",
    path: "/reports/accounts/unadjusted-transactions",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA019",
    label: "Creditors Bill Statement Report",
    path: "/reports/accounts/creditors-bill-statement",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA020",
    label: "Debit / Credit Note Statement Summary",
    path: "/reports/accounts/debit-credit-note-statement",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA021",
    label: "Unapproved Voucher Logs",
    path: "/reports/accounts/unapproved-vouchers",
    parent: "RA0001",
    active: true,
  },
  {
    id: "RAA022",
    label: "Master System Code Matrix List",
    path: "/reports/accounts/master-code-list",
    parent: "RA0001",
    active: true,
  },
];
