spring:
  application:
    name: backend
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=practice;encrypt=true;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: mssql12345
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true